// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "P60 Cannabis",
  domain: "p60cannabis.com",
  city: "York",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-york",
  address: "1938 Weston Rd, York, ON M9N 1W2",
  streetAddress: "1938 Weston Rd",
  postalCode: "M9N 1W2",
  phone: "(437) 522-2802",
  phoneIntl: "+14375222802",
  neighborhood: "Weston Road / York",
  nearbyAreas: ["Weston Road", "York", "Mount Dennis", "Keelesdale", "Eglinton West", "Black Creek", "Jane Street", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://p60cannabis.com/",
  mapEmbedUrl: "https://maps.google.com/maps?q=P60%20Cannabis%201938%20Weston%20Rd%2C%20York%2C%20ON%20M9N%201W2&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.7004400",
  longitude: "-79.5177900",
  hours: ["Open Daily: 10:00 AM - 03:00 AM"],
  seoTitle: "P60 Cannabis | Weed Dispensary in York",
  metaDescription: "P60 Cannabis is a local weed dispensary in York offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Weston Road", "York", "Mount Dennis"],
  introVariant: "Welcome to P60 Cannabis, your premier weed dispensary in York situated right on 1938 Weston Rd. We are dedicated to providing adults 19+ with top-tier weed, premium cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and CBD products. If you are looking for a trusted cannabis store near Weston Road / York or a weed shop near York, stop by today to consult with our knowledgeable staff.",
  neighborhoodDescription: "Located in the vibrant Weston Road / York district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking and municipal parking spaces are available nearby",
  transitNote: "Accessible by local TTC bus and transit routes serving Weston Road.",
  sectionTitle: "Serving Customers Near Weston Road and York"
};
