export const gbpLocation = {
  storeName: "P60 Cannabis",
  domain: "www.p60cannabis.com",
  city: "York",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-york",
  address: "1938 Weston Rd, York, ON M9N 1W2",
  streetAddress: "1938 Weston Rd",
  postalCode: "M9N 1W2",
  phone: "(437) 522-2802",
  phoneIntl: "+14375222802",
  neighborhood: "Weston Road / York",
  nearbyAreas: ["Weston Road", "York", "Mount Dennis", "Keelesdale", "Eglinton West", "Black Creek", "Jane Street", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.7004400",
  longitude: "-79.5177900",
  hours: ["Open Daily: 10:00 AM - 03:00 AM"],
  seoTitle: "P60 Cannabis | Weed Dispensary in York",
  metaDescription: "P60 Cannabis is a local weed dispensary in York offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Weston Road", "York", "Mount Dennis"],
  introVariant: "P60 Cannabis is a local weed dispensary in York at 1938 Weston Rd. Adults 19+ can browse menu categories including cannabis flower, pre-rolls, edibles, THC vapes, concentrates, CBD products, and accessories before visiting.",
  neighborhoodDescription: "Located in the vibrant Weston Road / York district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking and municipal parking spaces are available nearby",
  transitNote: "Accessible by local TTC bus and transit routes serving Weston Road.",
  sectionTitle: "Serving Customers Near Weston Road and York"
};
